#!/bin/bash

# An auto-update script to keep the system up-to-date. This is primarily useful
# for linkbotd upgrades, which will be frequent. This file (probably) belongs
# in /etc/cron.daily/
# Sleep for a random amount of time
SECONDS=`awk -v min=5 -v max=1800 'BEGIN{srand(); print int(min+rand()*(max-min+1))}'`
sleep $SECONDS
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -yq install linkbot-hub-files
DEBIAN_FRONTEND=noninteractive apt-get -yq install linkbotd
DEBIAN_FRONTEND=noninteractive apt-get -yq install linkbot-firmware
DEBIAN_FRONTEND=noninteractive apt-get -yq install liblinkbot
unattended-upgrade
apt-get autoclean
