#!/bin/sh

### BEGIN INIT INFO
# Provides:          barobo-startup
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This script runs the Barobo update scripts at startup.
### END INIT INFO

# Author: David Ko <david@barobo.com>

echo "cd /
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -yq install linkbot-hub-files
DEBIAN_FRONTEND=noninteractive apt-get -yq install linkbot-firmware
sleep 120
DEBIAN_FRONTEND=noninteractive apt-get -yq install linkbotd
DEBIAN_FRONTEND=noninteractive apt-get -yq install liblinkbot
unattended-upgrade
apt-get autoclean" | at now +5 minutes
